spring:
  application:
    name: nft_app
  profiles:
    active: DEV
  config:
    import: "optional:configserver:http://localhost:8888"
#  cloud:
#    config:
#      uri: http://localhost:8888
#      enabled: true
  security:
    user:
      name: admin
      password: password
      roles: ADMIN


management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info


logging:
  level:
    org:
      springframework:
        cloud: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId}] %-5level %logger{36} - %msg%n"