spring:
  application:
    name: nft_common
  profiles:
    active: DEV
  config:
    import:
      #      - classpath:configs/bonus-config.yml # https:<<config_server_url>>
      - optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/nft
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create # [none, validate, update, create, create-drop]
    show-sql: false